name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo apt-get install -y lua5.4

      - name: Read Toolkit Version
        id: read_version
        run: |
          toolkit_version=$(jq -r '.toolkit_version' version_control.json)
          echo "Toolkit Version: $toolkit_version"
          echo "toolkit_version=$toolkit_version" >> $GITHUB_OUTPUT

      - name: Build Toolkit
        run: |
          echo "Running build process for Retro Artist Toolkit Version ${{ steps.read_version.outputs.toolkit_version }}"
          cd $GITHUB_WORKSPACE/compiler && lua build_toolkit.lua

      - name: Zip Built Toolkit
        run: |
          mkdir -p dist
          zip -r dist/retro_artist_toolkit_v${{ steps.read_version.outputs.toolkit_version }}.zip $GITHUB_WORKSPACE/retro_artist_toolkit

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: retro_artist_toolkit_v${{ steps.read_version.outputs.toolkit_version }}.zip
          path: dist/retro_artist_toolkit_v${{ steps.read_version.outputs.toolkit_version }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo apt-get install -y lua5.4

      - name: Read Toolkit Version
        id: read_version
        run: |
          toolkit_version=$(jq -r '.toolkit_version' version_control.json)
          echo "Toolkit Version: $toolkit_version"
          echo "toolkit_version=$toolkit_version" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.read_version.outputs.toolkit_version }}
          release_name: "v${{ steps.read_version.outputs.toolkit_version }}"
          body: "Release of Retro Artist Toolkit version ${{ steps.read_version.outputs.toolkit_version }}"
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: dist/retro_artist_toolkit_v${{ steps.read_version.outputs.toolkit_version }}.zip
          asset_name: "retro_artist_toolkit_v${{ steps.read_version.outputs.toolkit_version }}.zip"
          asset_content_type: application/zip
