name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Lua
      uses: leafo/gh-actions-lua@v8
      with:
        lua-version: "5.4" # Specify your Lua version

    - name: Install dependencies
      run: luarocks install busted

    - name: Run tests
      run: busted tests
