name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lua5.4
        sudo apt-get install -y luarocks

    - name: Install Lua modules
      run: luarocks install busted --local

    - name: Add local LuaRocks to PATH
      run: echo "::add-path::$HOME/.luarocks/bin"

    - name: Run tests
      run: busted tests
