name: Publish to Wiki

on:
    push:
        paths:
            - wiki/**
        branches:
            - develop
    workflow_dispatch:
  
jobs:
    publish_to_wiki:
        name: Publish wiki folder to Wiki repository
        runs-on: ubuntu-latest
        steps:  
  
            - name: Checkout the repository
              uses: actions/checkout@v3
  
            - name: Publish to the repository
              uses: SwiftDocOrg/github-wiki-publish-action@v1
              with:
                path: "wiki"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}